// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heyurybzjpzqjrghixrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhleXVyeWJ6anB6cWpyZ2hpeHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzM2NzksImV4cCI6MjA2NDI0OTY3OX0.w1hTDAEpIPpl1a1MjJEbUya82BgWWXu747iPaCvyzJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);